# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(381, 273)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 150, 20))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 150, 20))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.input_name = QtWidgets.QLineEdit(Form)
        self.input_name.setGeometry(QtCore.QRect(170, 10, 200, 21))
        self.input_name.setObjectName("input_name")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 150, 20))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.input_info = QtWidgets.QLineEdit(Form)
        self.input_info.setGeometry(QtCore.QRect(170, 100, 200, 71))
        self.input_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.input_info.setObjectName("input_info")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 150, 20))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 150, 20))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 150, 20))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.input_stepeni = QtWidgets.QComboBox(Form)
        self.input_stepeni.setGeometry(QtCore.QRect(170, 40, 201, 22))
        self.input_stepeni.setObjectName("input_stepeni")
        self.input_stepeni.addItem("")
        self.input_stepeni.addItem("")
        self.input_stepeni.addItem("")
        self.input_zerna = QtWidgets.QComboBox(Form)
        self.input_zerna.setGeometry(QtCore.QRect(170, 70, 201, 22))
        self.input_zerna.setObjectName("input_zerna")
        self.input_zerna.addItem("")
        self.input_zerna.addItem("")
        self.input_price = QtWidgets.QSpinBox(Form)
        self.input_price.setGeometry(QtCore.QRect(170, 180, 201, 22))
        self.input_price.setMinimum(100)
        self.input_price.setMaximum(1000)
        self.input_price.setObjectName("input_price")
        self.input_v = QtWidgets.QSpinBox(Form)
        self.input_v.setGeometry(QtCore.QRect(170, 210, 201, 22))
        self.input_v.setMinimum(50)
        self.input_v.setMaximum(500)
        self.input_v.setSingleStep(50)
        self.input_v.setObjectName("input_v")
        self.btn_add = QtWidgets.QPushButton(Form)
        self.btn_add.setGeometry(QtCore.QRect(10, 240, 361, 21))
        self.btn_add.setObjectName("btn_add")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Создать"))
        self.label_2.setText(_translate("Form", "Hазвание сорта:"))
        self.label_7.setText(_translate("Form", "Oбъем упаковки:"))
        self.label_5.setText(_translate("Form", "Oписание вкуса:"))
        self.label_6.setText(_translate("Form", "Цена:"))
        self.label_4.setText(_translate("Form", "Mолотый/в зернах:"))
        self.label_3.setText(_translate("Form", "Cтепень обжарки:"))
        self.input_stepeni.setItemText(0, _translate("Form", "Светлая"))
        self.input_stepeni.setItemText(1, _translate("Form", "Средняя"))
        self.input_stepeni.setItemText(2, _translate("Form", "Темная"))
        self.input_zerna.setItemText(0, _translate("Form", "Молотый"))
        self.input_zerna.setItemText(1, _translate("Form", "В зернах"))
        self.btn_add.setText(_translate("Form", "Cоздать"))
